version: '3'


services:

  test_db:
    container_name: test_db
    hostname: test_db
    image: mysql:latest
    volumes:
      - ../volume/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
    restart: unless-stopped
  test_web:
    build: .
    ports:
      - 5000:5000
    networks:
      - default
    container_name:
      test_web
    depends_on:
      - test_db
networks:
  default:
    driver: bridge


